hard_tabs = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
version = "Two"
fn_params_layout = "Compressed"
#fn_call_width = 200
max_width = 120